resources:
  - ../../controller
namespace: atomist
secretGenerator:
- envs:
  - endpoint.env
  name: endpoint
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: policy-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: "ecr-atmtest"
images:
- name: atomist/adm-ctrl
  newTag: "v2"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
